### ISSUE TITLE
Can't recognize discord access token

### ISSUE THREAD

**Issue by RolesG** [kamui-7/discord-emote-menu#6] opened 2023-04-06 03:59 UTC
I can't get the script to recognize my discord access token. Does the script still work?

**Comment by kamui-fin** [comment] 2023-09-01 03:53
It should still indeed work without issues. Could you please share how you fetched the token?

**Comment by kamui-fin** [comment] 2023-09-01 04:01
Closing as I'm not able to reproduce on my end.

**Closed as completed by kamui-fin** 2023-09-01 04:01 UTC
